language: java

dist: xenial

jdk: openjdk8

services:
  - docker
  - xvfb

addons:
  sonarcloud:
    organization: "amathebest-github"
    token: 
      secure: "Lw9WUpCV91F6AwEbQlKQx5gGpMyZvJb4RVObVzK+IIzOuXHUVo1kQK+dG6lI6EQqaMgNbMdndjhi4cIn/t+oqaUJaE6UPatH//uJq5XFD3bKWLdyct208yEOfQf5qqhza7tSeE1AeOZZjsmcJhYMzFDzZKzmB2YtBcuO6DroNMQ91b02L+lh1IL7JhZzteCeU+19wXiWyS4EYoFe6A/fGnmiH9iMGZti+Slhajs8I6+XXf9ChYs1gSxGnYhonv6OMvgQq2iaZSpb++Ztv+NT1+NEA46PCyeMaAnx6/ZCFxhnnlKqgqtCtiI+5qcE1NRsviHVacql0NdnuRG9we12yMj+F4vUiq/T3VQUpaEShvp/BVoPoRrixNSwEfnzAjOQF2PATpGfvBKceNSrCHQ42LX1QukPZBDJmQEwwCpnrgs8bnPe3Z1THZkpm/MQaebhSnFrO0kAWZCV2Bw7DZ6cCEKFtFI6NYhkI3ACCgbNtWbfOirWTHRWQXLOwtGbkxHlBQQLsH6vxzsN5QtllF+hcxXH8yuWgWpJyQHzgww63LCPt2KVEk+y6HTrnbNwgSayUKVUj2ciQe/XYlSG8NbKGvZokV+DZp+kn/o58jD4wI/TlGtEK+hv5re5bscEnqgCBFWtPVhsdre2g4eAlji4hLv0IVjYS75Oy/tk+V7aRRE="

install: true

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

steps:
  - uses: actions/checkout@v2
    with:
    fetch-depth: 0

script:
  - mvn -f com.project.apt.gestionale/pom.xml clean verify -Pjacoco sonar:sonar
